project:
  type: website
  output-dir: docs

website:
  title: "geospatial0523"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: dayone.qmd
        text: Day One
      - href: daytwo.qmd
        text: Day Two
      - href: recordings.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

